spring.application.name=tenant-service-node2
server.servlet.context-path=/tenant
server.port=8084
spring.datasource.url=jdbc:postgresql://localhost:5432/tenant2
spring.datasource.username=postgres
spring.datasource.password=Admin@123
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.default_schema=public
spring.jpa.properties.hibernate.jdbc.batch_size=1000
spring.jpa.properties.hibernate.show_sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.order_inserts=true
spring.jpa.properties.hibernate.id.new_generator_mappings=true
spring.jpa.properties.hibernate.generate_statistics=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=TRACE
logging.level.org.hibernate.engine.jdbc.batch.internal.AbstractBatchImpl=DEBUG
spring.jpa.open-in-view=false
spring.batch.jdbc.initialize-schema=always
spring.batch.job.enabled=true